import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Gallery from '@/components/Gallery';
import { Arrow, Asterisk, Globe } from '@/components/Icons';
import { categories } from '@/lib/content';

export default function Home() {
  return <div id="top">
    <Header />
    <main id="main">
      <section className="hero container" id="home">
        <div className="hero-copy"><span className="eyebrow hero-eyebrow"><span className="tiny-stitch" aria-hidden="true">＋</span> ROOTED IN TIRUPUR. REACHING THE WORLD.</span><h1>Made with<br/><em>care.</em> Worn<br/>everywhere.</h1><p>Premium knitwear. Thoughtful craftsmanship.<br className="desktop-break"/> Your trusted manufacturing partner since 1995.</p><div className="hero-actions"><a className="button button-dark" href="#products">Explore our products <Arrow diagonal /></a><a className="hero-story" href="#about">The Benso story <span aria-hidden="true">↘</span></a></div><div className="hero-origin"><span className="origin-rule"/><span>DESIGNED FOR LIFE. MADE FOR THE WORLD.</span></div></div>
        <div className="hero-visual"><Image className="hero-image" src="/images/knitwear-hero.webp" alt="An editorial arrangement of textured green and cream knitwear with cotton yarn" fill priority sizes="(max-width: 700px) 100vw, 50vw"/><div className="hero-image-top"><span>THE FABRIC OF BENSO</span><span>EST. 1995</span></div><div className="quality-label"><Asterisk /><span>GOOD PEOPLE.<br/>GREAT KNITWEAR.</span></div><div className="hero-image-bottom"><span>A little care in every thread.</span><span>KNITWEAR / INDIA</span></div></div>
      </section>

      <div className="promise-strip"><div className="container promise-inner"><span>Quality in every stitch</span><Asterisk/><span>Responsibly minded</span><Asterisk/><span>Globally connected</span><Asterisk/><span>Committed to on-time delivery</span><Asterisk/></div></div>

      <section id="about" className="section about-section"><div className="container"><div className="section-top"><span className="eyebrow"><span className="section-number">01</span> THE BENSO STORY</span><span className="section-side-note">GOOD PARTNERSHIPS START WITH GOOD PEOPLE.</span></div><div className="about-grid"><div className="about-image"><Image src="/images/gallery-2.webp" alt="Benso garment makers working at sewing machines in Tirupur" fill sizes="(max-width: 700px) 90vw, 45vw"/><div className="est-label"><span>Our story began in</span><strong>1995<span>↗</span></strong><span>TIRUPUR, INDIA</span></div></div><div className="about-copy"><h2>Great garments.<br/>Even better<br/><em>relationships.</em></h2><p>We’re Benso Garment Pvt Ltd — knitwear manufacturers and exporters from Tirupur, the heart of India’s knitted garment industry.</p><p>Since 1995, we’ve brought care, skill and consistency to garments for women, men, children and infants. Our integrated manufacturing setup helps us keep a close eye on quality, every step of the way.</p><p>For us, it’s about more than making garments. It’s about transparent partnerships, responsible practices, and doing what we say we’ll do.</p><a className="text-link" href="#directors">Meet the people behind Benso <Arrow diagonal /></a></div></div><div className="values-row"><div><strong>Since ’95</strong><span>A foundation of experience</span></div><div><strong>4 categories</strong><span>Knitwear for every generation</span></div><div><strong>7 markets</strong><span>Connected across the world</span></div><div><strong>One promise</strong><span>Care, from start to finish</span></div></div></div></section>

      <section id="products" className="section products-section"><div className="container"><div className="section-top"><span className="eyebrow"><span className="section-number">02</span> WHAT WE MAKE</span><span className="section-side-note">DIFFERENT PEOPLE. THE SAME ATTENTION TO DETAIL.</span></div><div className="section-heading-row"><h2>For every day.<br/>For <em>everyone.</em></h2><p>From little firsts to everyday favourites.<br/>Discover knitwear made with a common thread of quality.</p></div><div className="product-grid">{categories.map((category, index) => <Link key={category.slug} href={`/products/${category.slug}/`} className={`product-card product-${category.color}`}><div className="product-image"><Image src={`/images/${category.image}.png`} alt={category.title} fill sizes="(max-width: 600px) 45vw, (max-width: 900px) 43vw, 24vw"/><span className="product-index">0{index + 1}</span><span className="product-action"><Arrow diagonal /></span></div><div className="product-title"><h3>{category.title}</h3><Arrow diagonal /></div><p>{category.label}</p></Link>)}</div></div></section>

      <section id="markets" className="markets-section"><div className="container"><div className="section-top"><span className="eyebrow"><span className="section-number">03</span> OUR GLOBAL FOOTPRINT</span><Globe/></div><div className="markets-grid"><div><h2>Made in Tirupur.<br/>At home in<br/><em>the world.</em></h2><p>Local roots. International relationships. We bring premium knitwear to brands and retailers across Europe and North America.</p><div className="market-origin"><span className="origin-symbol"><Asterisk/></span><div><strong>Tirupur, India</strong><span>Where every partnership begins</span></div></div></div><div className="market-list"><span className="market-list-label">OUR EXPORT MARKETS</span>{[['United Kingdom', 'GB'], ['United States', 'US'], ['Italy', 'IT'], ['Turkey', 'TR'], ['Germany', 'DE'], ['France', 'FR'], ['Spain', 'ES']].map(([name, code], index) => <div className="market-row" key={code}><span className="market-number">0{index + 1}</span><span>{name}</span><span className="market-code">{code}</span></div>)}</div></div><div className="market-bottom"><span>Strong relationships. Consistent quality. Reliable delivery.</span><a href="#contact">Let’s work together <Arrow diagonal/></a></div></div></section>

      <Gallery />

      <section id="directors" className="section team-section"><div className="container"><div className="section-top"><span className="eyebrow"><span className="section-number">05</span> THE PEOPLE BEHIND THE PROMISE</span><span className="section-side-note">OUR STRENGTH IS OUR TEAM.</span></div><div className="team-grid"><div className="team-copy"><h2>Experience leads.<br/><em>People make it.</em></h2><p>Guided by M. Balasubamaniam and V. Mageswari, Benso is built on decades of knowledge in knitted garment manufacturing, sourcing and global exports.</p><p>Our leadership’s focus on ethical production, a skilled workforce and lasting client relationships is woven into everything we do.</p><div className="directors"><div><strong>M. Balasubamaniam</strong><span>Leadership</span></div><div><strong>V. Mageswari</strong><span>Leadership</span></div></div></div><figure className="team-photo"><div><Image src="/images/team.webp" alt="The Benso Garment team gathered together" fill sizes="(max-width: 700px) 90vw, 48vw"/></div><figcaption><span>Many hands. One shared commitment.</span><Asterisk /></figcaption></figure></div></div></section>
    </main>
    <Footer />
  </div>;
}
